Task 1 
The Titanic data set, provided in XML format on Moodle, It provides information about passengers on board the
RMS Titanic, including whether they survived or not.
(a) Create a function to import this XML file. Your function must include appropriate exception handling
clauses covering all possible error conditions and should return the parsed contents of the
XML file

In [24]:
import xml.etree.ElementTree as ET

def parse_xml_file(file_path):
    try:
        # Parse the XML file
        tree = ET.parse(file_path)
        root = tree.getroot()

        # Return the parsed contents
        return root
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
    except ET.ParseError as e:
        print(f"Error parsing XML: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

    # Return None in case of any exception
    return None

# Example usage:
file_path = "dataset.xml"
parsed_xml = parse_xml_file(file_path)
if parsed_xml is not None:
    # You can work with the parsed XML here
    print(ET.tostring(parsed_xml, encoding='utf8').decode('utf8'))


<?xml version='1.0' encoding='utf8'?>
<data>
  <row>
    <index>0</index>
    <PassengerId>1</PassengerId>
    <Survived>0</Survived>
    <Pclass>3</Pclass>
    <Name>Braund, Mr. Owen Harris</Name>
    <Sex>male</Sex>
    <Age>22.0</Age>
    <SibSp>1</SibSp>
    <Parch>0</Parch>
    <Ticket>A/5 21171</Ticket>
    <Fare>7.25</Fare>
    <Cabin />
    <Embarked>S</Embarked>
  </row>
  <row>
    <index>1</index>
    <PassengerId>2</PassengerId>
    <Survived>1</Survived>
    <Pclass>1</Pclass>
    <Name>Cumings, Mrs. John Bradley (Florence Briggs Thayer)</Name>
    <Sex>female</Sex>
    <Age>38.0</Age>
    <SibSp>1</SibSp>
    <Parch>0</Parch>
    <Ticket>PC 17599</Ticket>
    <Fare>71.2833</Fare>
    <Cabin>C85</Cabin>
    <Embarked>C</Embarked>
  </row>
  <row>
    <index>2</index>
    <PassengerId>3</PassengerId>
    <Survived>1</Survived>
    <Pclass>3</Pclass>
    <Name>Heikkinen, Miss. Laina</Name>
    <Sex>female</Sex>
    <Age>26.0</Age>
    <SibSp>0</SibSp>
    <Parch>0</Parch>
  

b) Using the function you created in a) above, load the XML file. Then use the print() function to display the
Gender and the name for the second, fourth, eighth, sixteenth, and thirty-second passengers.

In [25]:
file_path = "dataset.xml"  # Replace with the path to your XML file
parsed_xml = parse_xml_file(file_path)

if parsed_xml is not None:
    # Extract and print the gender and name of specific passengers
    passengers = parsed_xml.findall("row")

    for index in [1, 3, 7, 15, 31]:
        if index < len(passengers):
            passenger = passengers[index]
            gender = passenger.find("Sex").text
            name = passenger.find("Name").text

            print(f"Passenger {index + 1}:")
            print(f"Gender: {gender}")
            print(f"Name: {name}")
            print()
        else:
            print(f"Passenger {index + 1} does not exist in the XML.")


Passenger 2:
Gender: female
Name: Cumings, Mrs. John Bradley (Florence Briggs Thayer)

Passenger 4:
Gender: female
Name: Futrelle, Mrs. Jacques Heath (Lily May Peel)

Passenger 8:
Gender: male
Name: Palsson, Master. Gosta Leonard

Passenger 16:
Gender: female
Name: Hewlett, Mrs. (Mary D Kingcome) 

Passenger 32:
Gender: female
Name: Spencer, Mrs. William Augustus (Marie Eugenie)



(d) For all passengers where the age less than 30 and Class = 1 or 2, if they survived then extract the fields
below and save them to a CSV file. Note that you should not use Pandas for this task.
• Gender
• Name
• Cabin
• Ticket
• PassengerId
Your code should contain appropriate exception handling clauses and the exported CSV file should contain the
column names

In [26]:
import csv
def save_selected_passengers_to_csv(records):
    # Create or open a CSV file for writing
    with open('selected_passengers.csv', 'w', newline='') as csv_file:
        csv_writer = csv.writer(csv_file)

        # Write the header row to the CSV file
        header = ["Gender", "Name", "Cabin", "Ticket", "PassengerId"]
        csv_writer.writerow(header)

        for record in records:
            age_element = record.find("Age")
            age = float(age_element.text) if age_element is not None and age_element.text is not None else None
            pclass = int(record.find("Pclass").text)
            survived = int(record.find("Survived").text)

            if age is not None and age < 30 and pclass in [1, 2] and survived == 1:
                gender = record.find("Sex").text
                name = record.find("Name").text
                cabin = record.find("Cabin").text
                ticket = record.find("Ticket").text
                passenger_id = record.find("PassengerId").text

                csv_writer.writerow([gender, name, cabin, ticket, passenger_id])

# Load the XML file
file_path = "dataset.xml"  # Replace with the path to your XML file
parsed_xml = parse_xml_file(file_path)

if parsed_xml is not None:
    # Extract and save selected passengers to a CSV file
    passengers = parsed_xml.findall("row")
    save_selected_passengers_to_csv(passengers)

print("Selected passengers have been saved to 'selected_passengers.csv'.")


Selected passengers have been saved to 'selected_passengers.csv'.


## Task 2

a) Take two 3D matrices, Matrix1 and Matrix2, each with dimensions 3x3x3. You want to perform the
following operations on these matrices: (Note: use same value given below)
1. Extract the diagonal from the each dimension of each matrix.
2. Take sum of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D

In [27]:
import numpy as np

In [28]:
matrix = np.zeros((3, 3, 3))

In [29]:
values = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
          [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]
Matrix1 = np.array(values)

In [31]:
matrix2 = np.zeros((3, 3, 3))

In [35]:
values = [[[9, 8, 7], [6, 5, 4], [3, 2, 1]],
          [[27, 26, 25], [24, 23, 22], [21, 20, 19]],
         [[18, 17, 16], [15, 14, 13], [12, 11, 10]]]
Matrix2 = np.array(values)

In [33]:
Matrix1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [36]:
Matrix2

array([[[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]],

       [[27, 26, 25],
        [24, 23, 22],
        [21, 20, 19]],

       [[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]]])

1. Extract the diagonal from the each dimension of each matrix.

In [38]:
import numpy as np

# Assuming you have Matrix1 and Matrix2 defined

# Extract the diagonal from each dimension of Matrix1
diagonal1 = np.diagonal(Matrix1, axis1=1, axis2=2) 

# Extract the diagonal from each dimension of Matrix2
diagonal2 = np.diagonal(Matrix2, axis1=1, axis2=2)  


In [40]:
diagonal1

array([[ 1,  5,  9],
       [10, 14, 18],
       [19, 23, 27]])

In [41]:
diagonal2

array([[ 9,  5,  1],
       [27, 23, 19],
       [18, 14, 10]])

In [39]:
diagnal_sum=diagonal1+diagonal2

In [42]:
diagnal_sum

array([[10, 10, 10],
       [37, 37, 37],
       [37, 37, 37]])


(b) Take product of diagonals obtained from Matrix1 and Matrix2 element-wise to get a new 2D matrix

In [46]:
diagnal_product= diagonal1 * diagonal2

In [47]:
diagnal_product

array([[  9,  25,   9],
       [270, 322, 342],
       [342, 322, 270]])

(C) Calculate the sum of all the elements in the resulting product

In [48]:
sum_Matrix=np.sum(diagnal_product)

In [49]:
sum_Matrix

1911

d) Calculate the variance of the values in the flattened (1D) version of the matrices. Hint use Numpy var
function

In [55]:
flattened_matrix = Matrix1.flatten()

# Calculate the variance of the flattened values
variance1 = np.var(flattened_matrix)


In [56]:
variance1

60.666666666666664

In [57]:
flattened_matrix = Matrix2.flatten()

# Calculate the variance of the flattened values
variance2 = np.var(flattened_matrix)


In [58]:
variance2

60.666666666666664

Create two new ndarrays each containing 10 values. The first should have evenly spaced values from 20
to 60. The second should contain evenly spaced values from 10 to 30. Add together corresponding array
entry values from each of the two arrays, i.e. perform the addition element-wise.

In [59]:
array1 = np.linspace(20, 60, 10)
array2 = np.linspace(10, 30, 10)
result = array1 + array2


In [60]:
result

array([30.        , 36.66666667, 43.33333333, 50.        , 56.66666667,
       63.33333333, 70.        , 76.66666667, 83.33333333, 90.        ])